# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "The CAD Coder"
title_separator: "-"
email: your-email@example.com
description: "Programming Tutorials for SOLIDWORKS 3D CAD Software."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/logo.png"

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : google # lunr (default), algolia
google:
  search_engine_id       : 4b2b9cb8c831ee0fb # YOUR_SEARCH_ENGINE_ID
  instant_search         : true # false (default), true

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-117501871-2" # Replace this with your ID, or delete
    anonymize_ip         : true

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-2x fa-twitter-square"
      # url: https://twitter.com/CadCoder
    - label: "Facebook"
      icon: "fab fa-2x fa-facebook-f"
      url: https://facebook.com/thecadcoder
    - label: "GitHub"
      icon: "fab fa-2x fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-2x fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-2x fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-2x fa-youtube-play"
      # url:
    - label: "YouTube"
      icon: "fab fa-2x fa-youtube"
      url: https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg
    - label: "Email"
      icon: "fa fa-envelope fa-2x"
      url: "mailto:thecadcoder@gmail.com"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  vba:
    output: true
    permalink: /:collection/:path/
  solidworks-cpp:
    output: true
    permalink: /:collection/:path/
  solidworks-macros:
    output: true
    permalink: /:collection/:path/
  solidworks-csharp:
    output: true
    permalink: /:collection/:path/
  drafts:
    output: true
    permalink: /:collection/:path/
  inventor-csharp:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _vba
  - scope:
      path: ""
      type: vba
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      nav_name:   VBA
      sidebar:
          nav: "vba"
  # _solidworks-cpp
  - scope:
      path: ""
      type: solidworks-cpp
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      nav_name:   Solidworks C++ API
      sidebar:
          nav: "solidworks-cpp"
  # _solidworks-macros
  - scope:
      path: ""
      type: solidworks-macros
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      nav_name:   Solidworks VBA Macro
      sidebar:
          nav: "solidworks-macros"
  # _solidworks-csharp
  - scope:
      path: ""
      type: solidworks-csharp
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      nav_name:   Solidworks C# API
      sidebar:
          nav: "solidworks-csharp"
  # _drafts
  - scope:
      path: ""
      type: drafts
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      sidebar:
          nav: "solidworks-macros"
  # _inventor-csharp
  - scope:
      path: ""
      type: inventor-csharp
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_sticky: true       
      sidebar:
          nav: "inventor-csharp"

# Conversion
markdown: kramdown
highlighter: rouge
menuNumber: 1


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

timezone: America/New_York

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
