#-------------------------------
# General Site Settings

title: THE CAD CODER
description: Free VBA Tutorials for SOLIDWORKS 3D Software Macro Programming. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Author
author-avatar: author.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/thecadcoder # Add your Facebook handle
twitter:   https://twitter.com/CadCoder # Add your Facebook handle
youtube:   https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg # Add your YouTube Channel handle
email:   thecadcoder@gmail.com # Add your E-mail Address
# instagram: https://www.instagram.com/ # Add your Facebook handle
# pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-117501871-2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
# permalink: ':title/'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
